server:
  port: 10009  #该模块提供服务的端口（必须）
spring:
  application:
    name: sparkEntrance  #模块名，用于做高可用（必须）

#指定eureka Server的地址，用于注册（必须）
eureka:
  client:
    serviceUrl:
      defaultZone: locahost
  instance:
    metadata-map:
      test: enjoyyin
#（必须）
management:
  endpoints:
    web:
      exposure:
        include: refresh,info
logging:
  config: classpath:log4j2.xml
#    register-with-eureka: false
#    fetch-registry: false