server:
  port: 9001
spring:
  application:
    name: DataWorkCloud-Gateway
  cloud:
    gateway:
      routes:
        - id: dws
          uri: http://localhost:port/
          predicates:
          - Path=/dws/
        - id: dws/vg
          uri: http://localhost:port/
          predicates:
          - Path=/dws/vg/
        - id: dws/easyide
          uri: http://localhost:port/
          predicates:
          - Path=/dws/easyide/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:port/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    metadata-map:
      test: wedatasphere

management:
  endpoints:
    web:
      exposure:
        include: refresh,info
uc:
  login:
    url: http://innerauth.weizhipin.com/iuc/user/login
    system:
      token: datastar
#登录获取用户名接口配置
zk_registry: 172.18.209.78:2181,172.18.192.166:2181,172.18.209.79:2181,172.18.192.179:2181,172.18.209.92:2181,172.18.209.94:2181,172.18.192.184:2181